theme: minima
title: Megan's Blog
author: Megan
email: Spottedeye2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Megan's Blog where I write about random stuff. Come say hi!

# social links
twitter_username: SpottedHeart14
github_username:  MeganDoesCode

show_excerpts: true # set to false to remove excerpts on the homepage
